name: Formatter

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - run: git branch
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup ReSharper
      run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
    - name: Clean up
      run: jb cleanupcode Fuel-Georgia-Parser.sln
    - name: Set user
      run: |
        git config user.name cleanup-bot
        git config user.email cleanup-bot@every.bot
    - name: Stage files
      run: git add .
    - name: Commit
      run: git commit -m "cleanup"
    - name: Push
      run: git push
