name: Formatter

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run: git branch
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup ReSharper
      run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
    - name: Clean up
      run: jb cleanupcode Fuel-Georgia-Parser.sln
    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet; then echo "false"; else echo "true"; fi)
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config user.name cleanup-bot
        git config user.email cleanup-bot@every.bot
        git add .
        git commit -m "cleanup"
        git push
